### PR TITLE
use Mocha constructor find mocha

### PR DESCRIPTION
**Pull request by magicdawn**
#24 related

### CODE REVIEW

**Comment by blakeembrey** [comment]
@magicdawn I might need to get a matrix of `mocha` versions for CI running before merging this one, sorry - don't want to break compatibility down the stack.

**Comment by welladamm** [comment]
@blakeembrey where are we on this one? It's been a while now. :)

**Comment by blakeembrey** [comment]
@welladamm Sorry, I took a break and have been meaning to get back to this. The only thing I would need to add is the matrix of tests to CI to make sure older mocha versions continue working. I can do it tonight.

**Comment by welladamm** [comment]
@blakeembrey Good to know! 👍

**Comment by blakeembrey** [comment]
Closed with https://github.com/blakeembrey/co-mocha/commit/532a9e4a13731561bff61067ce422872bd385542.

**Pull request closed without merging**
