### PR TITLE
chore: upgrade peerDependencies supporting mocha@3

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Kind of redundant to say `<3` and then cancel that out by saying `>3`. Why not just use `<4`? With the current change the version would mean nothing, since `<3 || >3` is `true`.

**Comment by popomore** [comment]
because mocha3 is just under beta, will not be calculated into >3 or <4
Blake Embrey <notifications@github.com>于2016年7月31日 周日上午11:26写道：

**Comment by blakeembrey** [comment]
Please read my comment, I can not accept this. You've specified any version `<3 || >3` which **is every single version and defeats the purpose of specifying a version**.

**Comment by blakeembrey** [comment]
image

Unless you fix this, I won't accept it.

**Comment by popomore** [comment]
I have update my commit that only limit to 3. It can be updated to `">=1.18 <4` when mocha makes 3 stable.

**Comment by MarkHerhold** [comment]
Mocha 3 was released, so perhaps we can get away with just `">=1.18 <4"` now? I don't see any reason to explicitly allow the beta versions now.

**Comment by MarkHerhold** [comment]
I'd like to see get something merged if possible and stop beating around the bush. Here's a simple PR with <4 as per my comment above.
https://github.com/blakeembrey/co-mocha/pull/21

@blakeembrey If you don't want it just close it please. Thanks! :heart:

**Comment by blakeembrey** [comment]
I merged the `<4` change, it's a nicer change than trying to support pre-release versions. The practice of trying to support betas really drives my head around, since the versioning is tricky to get right and the usefulness seems minimal.

**Comment by popomore** [comment]
Yeah, That's I want. I don't know mocha will release soon.

Thx @MarkHerhold

**Pull request closed without merging**
